#!/bin/bash
jupyter contrib nbextension install --user

# enable Notebook extensions
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main
jupyter nbextension install --py --symlink --sys-prefix ipympl
jupyter nbextension enable --py --sys-prefix ipympl

# enable Lab extensions
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib

# Notebooks w/ extensions that auto-run code must be "trusted" to work the first time
jupyter trust z_dist_fit_10_nov.ipynb

